"""Deterministic AST security guardrail using sqlglot."""

import sqlglot
from sqlglot import exp

from sql_circuit_guard.core.schemas import ASTValidationResult


class ASTGuardrail:
    """Read-only SQL validator that inspects Abstract Syntax Trees."""

    FORBIDDEN_EXPRESSIONS: tuple[type[exp.Expression], ...] = (
        exp.Insert,
        exp.Update,
        exp.Delete,
        exp.Drop,
        exp.Alter,
        exp.Create,
        exp.Command,
        exp.Transaction,
    )

    def __init__(self, dialect: str = "sqlite") -> None:
        self.dialect = dialect

    def validate(self, raw_sql: str) -> ASTValidationResult:
        """Parse SQL and enforce strict single-statement SELECT-only rules.

        Args:
            raw_sql: Unvalidated SQL string generated by LLM.

        Returns:
            ASTValidationResult: Typed outcome indicating pass/fail with cause.
        """
        stripped_sql = raw_sql.strip()
        if not stripped_sql:
            return ASTValidationResult(
                is_valid=False,
                error_message="Empty SQL string provided.",
                violated_rule="EMPTY_QUERY",
            )

        try:
            # Parse into a list of sqlglot expression trees
            parsed_statements = sqlglot.parse(stripped_sql, read=self.dialect)
        except sqlglot.errors.ParseError as exc:
            return ASTValidationResult(
                is_valid=False,
                error_message=f"SQL syntax parse failure: {exc}",
                violated_rule="SYNTAX_PARSE_ERROR",
            )

        # Enforce single statement limit (prevents SQL injection stacking)
        valid_statements = [stmt for stmt in parsed_statements if stmt is not None]
        if len(valid_statements) != 1:
            return ASTValidationResult(
                is_valid=False,
                error_message=f"Expected exactly 1 statement, found {len(valid_statements)}.",
                violated_rule="MULTI_STATEMENT_BLOCKED",
            )

        root_node = valid_statements[0]

        # Enforce root node must be a SELECT expression
        if not isinstance(root_node, exp.Select):
            # Check if the root node is a Command type (e.g., VACUUM)
            if isinstance(root_node, exp.Command):
                return ASTValidationResult(
                    is_valid=False,
                    error_message=f"Root statement must be SELECT, got: {type(root_node).__name__}",
                    violated_rule="NON_SELECT_ROOT_BLOCKED",
                )
            # Check if the root node is one of the forbidden mutation/DDL node types
            for forbidden_type in self.FORBIDDEN_EXPRESSIONS:
                if isinstance(root_node, forbidden_type):
                    return ASTValidationResult(
                        is_valid=False,
                        error_message=f"Forbidden mutation AST node detected: {forbidden_type.__name__}",
                        violated_rule="MUTATION_BLOCKED",
                    )
            # If not a forbidden type, return NON_SELECT_ROOT_BLOCKED
            return ASTValidationResult(
                is_valid=False,
                error_message=f"Root statement must be SELECT, got: {type(root_node).__name__}",
                violated_rule="NON_SELECT_ROOT_BLOCKED",
            )

        # Check for explicitly forbidden mutation/DDL node types within the SELECT statement
        for forbidden_type in self.FORBIDDEN_EXPRESSIONS:
            if root_node.find(forbidden_type):
                return ASTValidationResult(
                    is_valid=False,
                    error_message=f"Forbidden mutation AST node detected: {forbidden_type.__name__}",
                    violated_rule="MUTATION_BLOCKED",
                )

        # Transpile clean normalized SQLite dialect string
        normalized_sql = root_node.sql(dialect=self.dialect)

        return ASTValidationResult(
            is_valid=True,
            sanitized_sql=normalized_sql,
        )
